mod armstrong_number;
mod beer_song;
mod difference_of_squares;
mod gigasecond;
mod isbn_verifier;
mod isogram;
mod lucians_luscious_lasagna;
mod nucleotide_count;
mod protein_translation;
mod robot_name;
mod simple_cipher;
mod word_count;

pub use armstrong_number::*;
pub use beer_song::*;
pub use difference_of_squares::*;
pub use gigasecond::*;
pub use isbn_verifier::*;
pub use isogram::*;
pub use lucians_luscious_lasagna::*;
pub use nucleotide_count::*;
pub use protein_translation::*;
pub use robot_name::*;
pub use simple_cipher::*;
pub use word_count::*;
